name = "FcRegression"
uuid = "12d3ff75-5241-45b7-b303-d29cf6c8f34b"
authors = ["Aaron Meyer <a@asmlab.org>", "Cyrillus Tan", "Robert Theisen", "Stephen Lees"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Impute = "f7bf1975-0170-51b9-8c5f-a992d46b9575"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
polyBindingModel = "d8b71a59-0ce5-46cb-870e-e9e7240c6f77"

[extras]
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Profile", "Random"]
